### ISSUE TITLE
CMD+V not CTRL+V to paste on MacOS

### ISSUE THREAD

**Issue by greerso** [zelcash/zelcash-swing-wallet#10]
In V7.0.1 of the Zelcash Swing Wallet for MacOS, pasting text requires CTRL+V instead of CMD+V.  This is a Windows shortcut, not MacOS.  There are no other options for paste such as edit menu or right click, pasting an address requires knowing to use the Windows shortcut.

**Comment by Cabecinha84** [comment]
It was fixed and will be available on the next zelmate release.
